version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - auth
  redis:
    image: redis:7.0
    container_name: auth-redis
    restart: always
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - auth
networks:
  auth:
    name: auth
    driver: bridge
